### PR TITLE
Add chart dependency support to the team label

### PR DESCRIPTION
**Pull request by QuentinBisson**
Tested [here](https://regex101.com/r/TQDrjZ/1) but it is my first time with Python and regex :D 

We are in dire need of this because we use subcharts a lot and if the annotation is not set on the subchart, the value is empty

@piontec can you take a look pretty please?

### CODE REVIEW

**Comment by QuentinBisson** [comment]
I'm not sure the issue in the tests is from my change TBH

**Review by piontec — COMMENTED** [review]
I haven't checked, but the regex seems to work in my eyes :D
I'm not sure about the motivation, though: is the case here that you want to make it possible for someone installing the app to override the owning team? This seems a bit weird: app is owned by a team, why to set it to something different?

**Comment by QuentinBisson** [comment]
Not really, the use case is that in atlas, we use chart dependencies to manage app upgrades to "only" have to upgrade the dependency, adapt the values file and not use the subtree which causes a lot of conflicts for us:
Here is an example PR https://github.com/giantswarm/prometheus-operator-app/pull/207/files


The issue with this approach is that the annotation `application.giantswarm.io/team` is not set on the subchart (here kube-prometheus-stack) and helm is then setting the value for the subchart templates to `""` and it's not taking the value from the root chart.

Being able to configure it also as a default would ensure we take the value from the chart if it exits but are able to override it if necessary (i.e. for subcharts that do not have the annotation set).

FYI: In the linked PR we are shadowing the `kube-prometheus-stack.labels` in the helpers.


With this change we can have:


root:
  Chart.yaml with annotation with default of atlas in helpers
  charts/
    chart1:
      Chart.yaml with *atlas* team annotation (team will be set to atlas as the default would not apply)
    chart2:
      Chart.yaml with *honeybadger* team annotation (team will be set to honeybadger as the default would not apply)
    chart3:
      Chart.yaml with *no team* annotation (team will be set to the default value, a.k.a. atlas)


Does that make sense?

**Review by piontec — APPROVED** [review]
Thanks for the explanation! Makes sense to dynamically set the team in subcharts :)

**Pull request merged**
