### PR TITLE
Add displayName and links to the schema

### PR DESCRIPTION
**Pull request by kopiczko**
Towards https://github.com/giantswarm/giantswarm/issues/20946

### CODE REVIEW

**Comment by kopiczko** [comment]
Note this is untested and I don't have intention to test it since I found an alternative solution.

**Comment by piontec** [comment]
@kopiczko Does this come from standard cilium chart? These fields are custom and not really part of standard described here: https://helm.sh/docs/topics/charts/#the-chartyaml-file
Still, we're adding our custom fields as well there... we have to think what to do about them :|

**Comment by kopiczko** [comment]
https://github.com/cilium/cilium/blob/774a91f0e7497d9c9085234005ec81f1065c3783/install/kubernetes/cilium/Chart.yaml#L3

**Comment by piontec** [comment]
OK, we had some discussion, and we decided not to add other's custom attributes to our schema. The main reason is that if we're going to add any arbitrary field to the schema, it's going to become one big mess and still doesn't solve the problem for any custom field.
The suggested solution here is to fork/branch source repo and remove cilium specific tags in there. Then, build your chart from there.
As such, I'm closing this PR, but feel free to reopen, ping us or shout at us if you still want to do something around it.

**Pull request closed without merging**
