### PR TITLE
Docs and fixes

### PR DESCRIPTION
**Pull request by piontec**
This includes:
 - some basic docs to get started
 - a fix for not working `--skip-tests` option

### CODE REVIEW

**Comment by ubergesundheit** [comment]
Docs look good!

IMO skipping multiple steps is still not possible without this patch:

```diff
diff --git a/app_build_suite/__main__.py b/app_build_suite/__main__.py
index 908f7b7..135acbd 100644
--- a/app_build_suite/__main__.py
+++ b/app_build_suite/__main__.py
@@ -62,14 +62,14 @@ def configure_global_options(config_parser: configargparse.ArgParser):
     steps_group = config_parser.add_mutually_exclusive_group()
     steps_group.add_argument(
         "--steps",
-        nargs="+",
+        action="append",
         help=f"List of steps to execute. Available steps: {ALL_STEPS}",
         required=False,
         default=["all"],
     )
     steps_group.add_argument(
         "--skip-steps",
-        nargs="+",
+        action="append",
         help=f"List of steps to skip. Available steps: {ALL_STEPS}",
         required=False,
         default=[],
```

**Comment by piontec** [comment]
How are you testing this? This seems to work fine...

```
dabs.sh -c examples/apps/hello-world-app --skip-steps test_unit test_performance 
2020-12-22 11:09:04,656 __main__ INFO: Starting build with the following options
2020-12-22 11:09:04,656 __main__ INFO: 
Command Line Args:   -c examples/apps/hello-world-app --skip-steps test_unit test_performance
Config File (examples/apps/hello-world-app/.abs/main.yaml):
  replace-chart-version-with-git:true
  generate-metadata: true
  catalog-base-url:  http://localhost/
Defaults:
  --build-engine:    helm3
  --steps:           ['all']
  --destination:     .
  --app-tests-deploy-namespace:default
  --app-tests-pytest-tests-dir:tests/abs
```

**Comment by piontec** [comment]
OK, I think you're using it like `--skip-steps a --skip-steps b` - this won't work. That's why I called them `--skip-steps`, not `--skip-step`. Do you think adding this info to docs is enough?

**Comment by ubergesundheit** [comment]
You're right, this would require users to specify the flag multiple times. Using `nargs='+'` prevents flags after the `--(skip-)steps` flag which IMO is not good UX.

My suggestion would be to allow specifying these flags multiple times or change it to allow receiving multiple values separated by a comma.

**Comment by piontec** [comment]
> You're right, this would require users to specify the flag multiple times. Using `nargs='+'` prevents flags after the `--(skip-)steps` flag which IMO is not good UX.

That's not true, AFAIR. It consumes all arguments until a new option is encountered (anything that starts with `-`). So should work.
 
> My suggestion would be to allow specifying these flags multiple times or change it to allow receiving multiple values separated by a comma.

Yeah, separated by comma would be nice, but frankly - I don't know how to do that easily. I think we can leave as it is for now and add info to the docs. WDYT?

**Review by ubergesundheit — APPROVED** [review]
LGTM. Docs are a good starting point

**Pull request merged**
